"""empty message

Revision ID: 545df6cabaf6
Revises: 4e2388f0bbc2
Create Date: 2020-01-02 12:51:22.617912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545df6cabaf6'
down_revision = '4e2388f0bbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    op.drop_column('task', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('user', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user'], ['id'])
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
